### PR TITLE
git_is_touched: Don't use git status --porcelain

### PR DESCRIPTION
**Pull request by faho**
That's the single most expensive git call you can make - it has to
scan the entire repo for *everything*.

This changes the time for e.g. a Qt clone from 500ms to 100ms.

See also https://github.com/oh-my-fish/oh-my-fish/pull/706.

### CODE REVIEW

**Comment by faho** [comment]
Alternatively, this could be `git_is_staged; or git_is_dirty`.

**Comment by jorgebucaran** [comment]
@faho Cool, thanks! Why not `git_is_staged; or git_is_dirty` then?

**Comment by faho** [comment]
Because I've seen them too late :smiley:. Want a new commit?

**Comment by jorgebucaran** [comment]
@faho Yes, please, whenever you can! 🎉

**Comment by faho** [comment]
Done.

**Comment by jorgebucaran** [comment]
Looks good to me! @stefanmaric Ping.

**Comment by stefanmaric** [comment]
Tests passed? Ship it. 😄

**Comment by jorgebucaran** [comment]
Great, thank you, @faho!

**Pull request merged**
